### PR TITLE
Enable title support for referenced ctools contents

### PR DESCRIPTION
**Pull request by axe312ger**

### CODE REVIEW

**Comment by yannickoo** [comment]
Please use `#states` in order to provide conditional fields :)

**Comment by axe312ger** [comment]
Here we go. Also fixes one small error.

**Comment by yannickoo** [comment]
Hmm, after checking your branch out I thought it would be better to alter the `ctools_block_content_type_edit_form` form in order to add the "Title wrapper" thing :/

**Comment by yannickoo** [comment]
Let's see whether we can fix that in #1.

**Comment by lslinnet** [comment]
This doesn't work if you allow multiple values for the field.

**Comment by axe312ger** [comment]
What exactly does not work? Can you do a more detailed bug report?

**Comment by lslinnet** [comment]
Given:
A node with a ctools_field which allows multiple values (tested with unlimited)

Expected:
1. Add a few values to a new node.
2. Hit the checkbox to change the title.
3. Change the title of the value where the checkbox was checked.

What happened was that the title input was revealed for all values.

**Pull request closed without merging**
